#!/bin/bash

case $1 in
    vb)
        args="s verbose"
        ;;
    v)
        args="sv"
        ;;
    vvb)
        args="sv verbose"
        ;;
    vstat)
        args="sv stats"
        ;;
    *)
        args="s"
        ;;
esac

java -jar misc/sparrow.jar $args
